package config

const (
	APP_NAME          = "APP_NAME"
	LOG_LEVEL         = "LOG_LEVEL"
	ENV               = "ENV"
	PORT              = "PORT"
	PORT_PRIVATE     = "PORT_PRIVATE"
	AWS_REGION        = "AWS_REGION"
	AWS_ENDPOINT      = "AWS_ENDPOINT"
	AWS_SECRET_PREFIX = "AWS_SECRET_PREFIX"
	AWS_SECRET_BATCH  = "AWS_SECRET_BATCH"
	SQLITE_DB_PATH    = "SQLITE_DB_PATH"
	JWT_PUBLIC_KEY    = "JWT_PUBLIC_KEY"
	JWT_ISSUER        = "JWT_ISSUER"
	JWT_AUDIENCE      = "JWT_AUDIENCE"
	JWT_KID           = "JWT_KID"
	RATE_LIMIT_RPS    = "RATE_LIMIT_RPS"
	RATE_LIMIT_BURST  = "RATE_LIMIT_BURST"
	IP_WHITELIST      = "IP_WHITELIST"
	IP_BLACKLIST      = "IP_BLACKLIST"
)
